[package]
name = "radix-leptos-popover"
description = "Leptos port of Radix Popover."
homepage = "https://radix.rustforweb.org/primitives/components/popover.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
leptos-node-ref.workspace = true
radix-leptos-compose-refs.workspace = true
radix-leptos-dismissable-layer.workspace = true
radix-leptos-focus-guards.workspace = true
radix-leptos-focus-scope.workspace = true
radix-leptos-id.workspace = true
radix-leptos-popper.workspace = true
radix-leptos-portal.workspace = true
radix-leptos-presence.workspace = true
radix-leptos-primitive.workspace = true
radix-leptos-use-controllable-state.workspace = true
js-sys = "0.3"
send_wrapper.workspace = true
wasm-bindgen = "0.2"
web-sys = { workspace = true, features = [
    "CssStyleDeclaration",
    "HtmlElement",
    "Node",
    "PointerEvent",
    "Window",
] }
