[package]
name = "radix-rect"
description = "Rust port of Radix Core Rect."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
wasm-bindgen = "0.2"
web-sys = { workspace = true, features = [
    "DomRect",
    "Element",
    "Window",
] }
