[package]
name = "radix-leptos-focus-scope"
description = "Leptos port of Radix Focus Scope."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
leptos-node-ref.workspace = true
once_cell = "1.19.0"
radix-leptos-compose-refs.workspace = true
radix-leptos-primitive.workspace = true
js-sys = "0.3"
send_wrapper.workspace = true
wasm-bindgen = "0.2"
web-sys = { workspace = true, features = [
    "CustomEvent",
    "CustomEventInit",
    "HtmlInputElement",
    "MutationObserver",
    "MutationObserverInit",
    "MutationRecord",
    "NodeFilter",
    "NodeList",
    "TreeWalker",
] }
