[package]
name = "radix-leptos-alert-dialog"
description = "Leptos port of Radix Alert Dialog."
homepage = "https://radix.rustforweb.org/primitives/components/alert-dialog.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
leptos-node-ref.workspace = true
radix-leptos-compose-refs.workspace = true
radix-leptos-dialog.workspace = true
radix-leptos-primitive.workspace = true
send_wrapper.workspace = true
web-sys = { workspace = true, features = [
    "Event",
    "CustomEvent",
    "HtmlElement",
    "KeyboardEvent",
] }
